### ISSUE TITLE
No such file or directory: './models/SMALL\\config.json'

### ISSUE THREAD

**Issue by weilifan** [wrmthorne/CycleNER#1]
When I run `python train.py --model_dir ./models/test_model --output_dir ./checkpoints/test_model --batch_size 64 --s2e_lr 3e-4 --e2s_lr 3e-4`, there is a error like followings. Could you tell me how to slove this? Thank you
with open(os.path.join(args.model_dir, 'config.json'), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './models/SMALL\\config.json'

**Comment by wrmthorne** [comment]
You haven't run the prepare script before trying to train. There are some sample commands in the README e.g.

```python
# prepare conll if you want to use conll instead of a custom dataset
python format_conll_data.py --s_examples 10000 --e_examples 1000

# prepare models, tokeniser, prefix, dataset etc.
python prepare.py --model_name test_model --model_dir ./models --train_dir ./data/train --eval_dir ./data/eval --test_dir ./data/test

# train the model
python train.py --model_dir ./models/test_model --output_dir ./checkpoints/test_model --batch_size 64 --s2e_lr 3e-4 --e2s_lr 3e-4

# generate samples
python generate.py --model_dir ./models/test_model --input "The man from Germany went to London to work for Google with his wife Henreitta Klein."
```

Hope this helps
